export const USER_REPOSITORY_SYMBOL = Symbol("USER_REPOSITORY_SYMBOL");
export const Product_REPOSITORY_SYMBOL = Symbol("PRODUCT_REPOSITORY_SYMBOL");
export const PURCHASE_ORDER_REPOSITORY_SYMBOL = Symbol(
	"PURCHASE_REPOSITORY_SYMBOL",
);
export const PURCHASE_ORDER_ITEMS_REPOSITORY_SYMBOL = Symbol(
	"PURCHASE_ORDER_ITEMS_REPOSITORY_SYMBOL",
);

export const WHAREHOUSE_REPOSITORY_SYMBOL = Symbol(
	"WAREHOUSE_REPOSITORY_SYMBOL",
);

export const INVENTORY_LEVEL_REPOSITORY_SYMBOL = Symbol(
	"INVENTORY_LEVEL_REPOSITORY_SYMBOL",
);

export const STOCK_MOVEMENT_REPOSITORY_SYMBOL = Symbol(
	"STOCK_MOVEMENT_REPOSITORY_SYMBOL",
);

export const SUPPLIER_REPOSITORY_SYMBOL = Symbol("SUPPLIER_REPOSITORY_SYMBOL");

export const PRODUCT_PRICE_REPOSITORY_SYMBOL = Symbol(
	"PRODUCT_PRICE_REPOSITORY_SYMBOL",
);

export const PRODUCT_BRAND_REPOSITORY_SYMBOL = Symbol(
	"PRODUCT_BRAND_REPOSITORY_SYMBOL",
);

export const PRODUCT_CATEGORY_REPOSITORY_SYMBOL = Symbol(
	"PRODUCT_CATEGORY_REPOSITORY_SYMBOL",
);
